### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by oscargarciajr** [aws-solutions/cognito-user-profiles-export-reference-architecture#23]
**Describe the bug**
Unable to deploy and keeps on doing a rollback on failed on step StackSetManagerCustomResource

Just Could not find the logs.

Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/11/10/[$LATEST]834097b97a704c80995f9251dee018b9 (RequestId: 75459652-7fa6-46d3-972e-b0c41acd1fdb)

Then it starts to rollback.
The following resource(s) failed to create: [StackSetManagerCustomResource]. Rollback requested by user.

**To Reproduce**
followed what is on the steps to deploy and deploying as is.

**Expected behavior**
Deployment Completed

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v1.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0126) - Cognito User Profiles Export Reference Architecture. Version **v1.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "cognito-user-profiles-export-reference-architecture/v1.0.0"
```

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by ericquinones** [comment]
Hi @oscargarciajr -

To help us troubleshoot, can you please let us know:
* What regions are you using?
  * What region are you deploying the solution in and also what region did you use as `SecondaryRegion` (CloudFormation Parameter)
  * Are you using the latest version of the solution (`v1.0.1`)?
  * Did you make any source code changes?

It would also be helpful to know the output of the CloudWatch Logs for the `StackSetManagerCustomResource`. That custom resource uses a Lambda function to perform some tasks. If you open the CloudWatch console and then use the left-side bar to open Logs > Log groups, you should be able to find the log groups for the Lambda functions deployed by the solution. You can use the filter bar at the top of the page to search for `/aws/lambda/`. The functions created by the solution should be prefixed with the name you gave to the CloudFormation stack during deployment. Open those log groups and search for the stream mentioned in the CloudFormation Events tab. If you are able to find that stream, please let us know if there are any particular errors reported there.

Thank you

**Comment by oscargarciajr** [comment]
Hi,

Thank you for the reply.

Primary Region: ap-northeast-1
Secondary Region: us-east-1

No Source Code Changes.

**Comment by oscargarciajr** [comment]
for some weird reasons, I re-deploy the stack again and reduce the name of the stack to few characters and it did deploy. so might be hitting the max numbers of characters for a resource.
