### ISSUE TITLE
Exporting and importing to and from a different account.

### ISSUE THREAD

**Issue by Warns** [aws-solutions/cognito-user-profiles-export-reference-architecture#24]
Ability to export and import Cognito user pool to and from a different account.

Basically importing Cognito user pool from account A in region `eu-west-1` to account B in region `eu-west-1` and/or secondary region `eu-central-1`.

**Comment by mikeols** [comment]
We are currently evaluating the roadmap and this has been incorporated into the considerations. Closing this for now.
