### ISSUE TITLE
Rewrite cloudformation with cdk

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [aws-solutions/cognito-user-profiles-export-reference-architecture#25]
**Is your feature request related to a problem? Please describe.**
I have to see a lot of code perform several operation by hand

**Describe the feature you'd like**
Using cdk with one command build will the best option: build/package code, run test, deploy resources
Also using CDK will decrease boilerplate code 10 times!

P.S. Many thanks for good solution anyway.

**Comment by mikeols** [comment]
Thank you for the feedback. Converting this to CDK is definitely a consideration going forward, but I cannot give a timeline at the moment. The feedback has been added to our roadmap so I will close this for now.
