### ISSUE TITLE
[question] Where second pool id is specified?

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [aws-solutions/cognito-user-profiles-export-reference-architecture#26]
I have deployed cloudformation stack from main region. And it deployed stack set in 2 regions main and secondary.
1) Is it enough?
2) I have not found any paramter for second cognito pool? Is it created automatically? Whre can I set it?

**Comment by kuromi-2022** [comment]
@C-h-e-r-r-y Hello. I had the same question and I think I figured it out, so thought I'd post it here. Once you have successfully deployed the cloudformation stack, it seems although ImportWorkflow is created it does not run automatically - you can run it yourself in either the Primary or Secondary region from Step Functions > State Machines > ImportWorkflow-XXXX > Start Execution. First, create an empty user pool to be the second Cognito user pool in primary/secondary region, and copy the id. Then when you start the execution of ImportWorkflow in that region, use the following as input:
{
  "NewUserPoolId": "<user pool id>"
}
This worked for me! Hope it helps.
