### ISSUE TITLE
add support for both "phone_number" and "email" as username attribute

### ISSUE THREAD

**Issue by joseantoniosouzadias** [aws-solutions/cognito-user-profiles-export-reference-architecture#51]
This is a severe restriction. Of the 11 user pools I looked at, 8 used both "phone_number" and "email" as username attribute, so using this code will not work.

We're attempting to create a DR solution by duplicating the environment in us-east-1 to us-west-2 without months of setup. This template showed promise, until we hit on this limitation.

Are there any plans to look into this option in the future?

**Comment by mikeols** [comment]
Hi @joseantoniosouzadias, there are no near-term feature releases planned for this solution. I can take your request and add it to the roadmap for evaluation, but unfortunately I cannot give a timeline yet.

**Comment by bios6** [comment]
Hi @joseantoniosouzadias ,

Cognito User Profiles Export Reference Architecture will no longer be supported starting on March 1, 2025 and will not receive any additional features. 

Thanks.
