### ISSUE TITLE
Import workflow does not work

### ISSUE THREAD

**Issue by dhmw** [aws-solutions/cognito-user-profiles-export-reference-architecture#58]
**Describe the bug**

When trying to restore a backup to a new user pool, the majority of user records cannot be imported. Most of the records from the pool I backed up fail with the following message:

```
[FAILED] Line Number NNNN - The User Record does not set any of the auto verified attributes to verified. (Example: email_verified to true).
```

I am unable to establish any configuration change in the target cognito pool which has any effect on this behaviour. I've tried almost all combinations of settings relating to sign-in and sign-up options and the import still fails.

More to the point, the import fails when I set up the new cognito pool with _exactly_ the same settings as the pool which was backed up.

**To Reproduce**

Back up a user pool which contains users with a mix of `email_verified` attribute values (missing, `true` and `false`) and then try to import it to a new user pool.

**Expected behavior**

I would expect all user records to be imported in as much the same state as in the original pool as possible.

**Please complete the following information about the solution:**

- [ ] Version: v1.0.5 / HEAD of master at https://github.com/aws-solutions/cognito-user-profiles-export-reference-architecture/tree/a923a3317b46de8dc9f4076ce15b667f89390262 
- [ ] Region: Export: us-east-1; Import eu-west-1
- [ ] Was the solution modified from the version published on this repository? Only in metadata.
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? No - could you please advise if this is relevant to the issue?
- [ ] Were there any errors in the CloudWatch Logs? Yes - see description above.

**Comment by dhmw** [comment]
Digging a bit further into this - I don't understand the auto verified attribute requirement here.

The import fails for any user with no `email_verified` attribute, or if the attribute is present and set to `false`.

However, I can _manually_ change the `email_verified` attribute to `true` OR `false` for _any existing user_.

It seems to me that the import job could actually import all users first setting `email_verified: true` and then doing a second pass to reset the values to `false` where appropriate?

Is it me, or is the import process just broken or incomplete?

**Comment by dhmw** [comment]
Hi @jrgaray27 I appreciate that this solution mirrors the underlying capabilities of Cognito itself.

However, it does seem that a 1:1 backup:restore can be achieved by first importing all users with `email_verified: true` and then doing a 2nd pass to reset the values to what they were originally.

Therefore, there is a deficiency in this solution to restore all data as much to its original state as possible.

If AWS (or those supporting AWS resources in public) don't seem to want to address this, it just adds another point to my list of grievances with Cognito and I should better spend my time looking for an alternative and a migration path away from Cognito.

Regards,
Doug.

**Comment by kroeter** [comment]
Hi Doug, 
Thank you for your comments, we appreciate your interest in improving this solution and will add your recommendation to our feature backlog. Unfortunately, we do not have any feature work dedicated to the roadmap for this solution through the remainder of the the year and so I don't see a path forward for achieving this functionality in the near term outside of the workaround that you mention in your comments above. 

Thanks again,

Kyle
